### ISSUE TITLE
Install via fork and Publish - error on execution index.js not found

### ISSUE THREAD

**Issue by MGana** [bryanbcook/azdevops-testplan-extension#25]
**Description**
I tried to use the exetesion following the instruction of this description
https://github.com/bryanbcook/deploymentqueuing-extension/blob/main/docs/Installation.md#fork-and-publish

I just published the extension and use it for my organization

when execting the tasks , I faced this error

##[error]File not found: '/home/vsts/work/_tasks/PublishTestPlanResults_9f8d55a9-9f5e-4e77-a924-2a48c17b65d7/0.1.0/index.js'

<img width="712" alt="image" src="https://github.com/bryanbcook/azdevops-testplan-extension/assets/21100403/4a47324f-23a5-491c-bfe2-f8fea97ad8c7">

```yaml
- task: PublishTestPlanResults@0
  inputs:
    testPlan: 'TestPlanTemplate'
    testResultFormat: 'jUnit'
    testResultFiles: 'results/combined-report.xml'
    testRunTitle: 'PublishedTestsResults'
```

**Environment Details**
- build-agent: microsoft-hosted
- test-format: jUnit 
- test-lanugage:   JavaScript 
- pipeline-format: yaml  

**Pipeline Output**

_provide output from the build with diagnostics enabled (system.debug variable set to 'true'). Mask secrets or sensitive information with xxx_:

```shell
Starting: PublishTestPlanResults
==============================================================================
Task         : Publish Test Plan Results
Description  : Publishes cross-platform test results (xUnit, JUnit) to an Azure DevOps Test Plan
Version      : 0.1.0
Author       : Bryan Cook
Help         : 
==============================================================================
##[error]File not found: '/home/vsts/work/_tasks/PublishTestPlanResults_xxxx-9f5e-4e77-a924-xxxxx/0.1.0/index.js'
Finishing: PublishTestPlanResults
```

**To Reproduce**
Steps to reproduce the behaviour:
1- Login to the [Marketplace (https://marketplace.visualstudio.com)](https://marketplace.visualstudio.com/) 
2- Click on the [Publish extensions](https://marketplace.visualstudio.com/manage) link
3 - Click on the Create Publisher button and fill in the basic details.
4- Clone the repository locally : https://github.com/bryanbcook/azdevops-testplan-extension
5- Install tfx extensions: npm install -g tfxcli
6 - Create the extension: tfx extension create -r src
7 - Upload the extension (*.vsix) to your publisher.
8 - Share the extension with your organization. 
9 - Use the extension in my pipeline

**Expected behaviour**

Any idea on how to fix this index.js issue

**Screenshots**

![image](https://github.com/bryanbcook/azdevops-testplan-extension/assets/21100403/91cce8fd-97d4-4214-b967-25d3d54dece0)

**Comment by bryanbcook** [comment]
Few observations:

1. The instructions I provided for the other extension will not work in this scenario. The other repository has no code to compile; This repository is TypeScript and needs to be compiled.
1. You made zero modifications to the unique identifiers in the vssextension.json or task.json. It's possible that you just created a duplicate in the marketplace and have broken my extension which will prevent me from making my extension public. **Please delete your extension!**
1. Publishing a duplicate is completely unnecessary and not supported as part of my private preview. In the other scenario, I cannot make the deployment queueing extension public because it contains a pipeline decorator which cannot be published  publicly for security reasons. This extension is simply not public because it's a private preview.

Please acknowledge when you have deleted your extension.

**Comment by MGana** [comment]
I deleted my extension
Thanks !
